[DBCluster] Implement ServerlessV2ScalingConfiguration
aws-cloudformation/aws-cloudformation-resource-providers-rds pull request #297
Opened 2022-08-31 17:58 UTC by osdrv

This commit adds a new attribute to DBCluter resource definition: `ServerlessV2ScalingConfiguration`. The motivation for this change is to catch up on the existing serverless configuration feature exposed by the SDK and CLI tool.

The teamplate structure is expected in the following format:
```yaml
  ServerlessV2ScalingConfiguration:
    MaxCapacity: <number>
    MinCapacity: <number>
```

The attribute itself is optional.

Documentation:
- https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-serverless-v2.html
- https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_ServerlessV2ScalingConfiguration.html

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

Signed-off-by: Oleg Sidorov <sidorovo@amazon.com>

2022-09-01 09:21 UTC, khebul commented on aws-rds-dbcluster/aws-rds-dbcluster.json
> +          "minimum": 0.5
Does it make sense to limit min capacity to [0.5, 128]?

2022-09-01 09:21 UTC, khebul commented on aws-rds-dbcluster/aws-rds-dbcluster.json
> +          "maximum": 128
Similar point to MaxCapacity: does it make sense to limit it to [0.5, 128]

2022-09-01 09:21 UTC, khebul commented on aws-rds-dbcluster/src/test/java/software/amazon/rds/dbcluster/AbstractHandlerTest.java
> +        SCALING_CONFIGURATION = ScalingConfiguration.builder()
nit: might be worth indicating that this configuration is for v1

2022-09-01 09:21 UTC, khebul commented on aws-rds-dbcluster/src/test/java/software/amazon/rds/dbcluster/CreateHandlerTest.java
> +        verify(rdsProxy.client(), times(3)).describeDBClusters(any(DescribeDbClustersRequest.class));
question: why for create there are 3 describes, while for other scenarios there are only 2?

2022-09-01 09:43 UTC, moataz-mhmd requested changes
I see there multiple scenario to upgrade cluster to serverless v2. I believe create handler will  be fine but update handler will be impacted and need to understand these scenarios and adopt with.  

Also these scenarios depend on the current engine type of DBCluster.
 
For example: 
To upgrade from Aurora serverless v1 to Aurora serverless v2
1. Create a DB cluster snapshot of the Aurora Serverless v1 cluster
2. Restore the snapshot to create a new, provisioned (that is, not Aurora Serverless) DB cluster running Aurora MySQL version 2.
3. Create a DB cluster snapshot of the provisioned Aurora MySQL version 2 cluster.
4. Restore the snapshot to create a new, provisioned DB cluster running Aurora MySQL version 3 that's compatible with Aurora Serverless v2, for example, 3.02.0.
5. Modify the writer DB instance of the provisioned DB cluster to use the Serverless v2 DB instance class.

Other option to simplify the change to support this feature as `createOnly` which will require replacement when customer modifying it. I think this might be acceptable as this new feature (no backward compatibility requirements) and we can define the initial behavior then we can enhance it in the future.

Ref: https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-serverless-v2.upgrade.html

2022-09-19 08:57 UTC, Outige approved these changes

2022-09-19 09:47 UTC, khebul submitted a review, later dismissed

2022-09-19 13:28 UTC, moataz-mhmd approved these changes

2022-09-26 08:12 UTC, khebul approved these changes

2022-09-26 08:15 UTC, moataz-mhmd approved these changes

2022-09-26 08:20 UTC, merged